# -*- coding: utf-8 -*-
"""2023.05.17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIuTOE9NSKFNGG9U9JQO4anFxh0tud7O
"""

name = input("이름을 입력하세요:")
print(name +"님 반갑습니다.")

a = int(input("숫자를 입력하세요:"))
b = int(input("숫자를 입력하세요:"))
print(a+b)

inch = float(input("인치(inch)를 입력하세요 : "))
cen = inch * 2.54
print("%.2f"%cen)

num1 = int(input("삼각형의 밑변 길이 : "))
num2 = int(input("삼각형의 높이 : "))
print("삼각형의 면적 :",(1/2)*num1*num2)

price = int(input("물건가격 : "))
buy = int(input("구매개수 : "))
pay = int(input("지불금액 : "))
result = (pay-(price*3))
print("거스름돈 : {} 원".format(result))

name = "홍길동"
age = 30
height = 171.5
print("성 : {}".format(name[0]))
print("이름 : {}".format(name[1:]))
print("홍길동의 나이 : {}세, 키 : {}".format(age,height))

a = [
    {"num":"1","name":"김철수","kor":90,"eng":80,"math":85,"total":0,"avg":0.0,"order":0},
    {"num":"2","name":"박제동","kor":90,"eng":85,"math":90,"total":0,"avg":0.0,"order":0},
    {"num":"3","name":"홍길동","kor":80,"eng":80,"math":80,"total":0,"avg":0.0,"order":0}
]
print(a[0])
print(a[0]["total"])
a[0]["total"] = 1
print(a[0])

a = [
    {"num":"1","name":"김철수","kor":90,"eng":80,"math":85,"total":0,"avg":0.0,"order":0},
    {"num":"2","name":"박제동","kor":90,"eng":85,"math":90,"total":0,"avg":0.0,"order":0},
    {"num":"3","name":"홍길동","kor":80,"eng":80,"math":80,"total":0,"avg":0.0,"order":0}
]
# 학생별 합계 구하기
aa = (a[0]["kor"]) + (a[0]["eng"]) + (a[0]["math"])
bb = (a[1]["kor"]) + (a[1]["eng"]) + (a[1]["math"])
cc = (a[2]["kor"]) + (a[2]["eng"]) + (a[2]["math"])
a[0]["total"] = 255
a[1]["total"] = 265
a[2]["total"] = 240

# 평균 구하기
aaa = (aa/3)
bbb = (bb/3)
ccc = (cc/3)
a[0]["avg"] = 85
a[1]["avg"] = 88
a[2]["avg"] = 80

print(a[0])
print(a[1])
print(a[2])

a = [
  {'num': '1', 'name': '김철수', 'kor': 90, 'eng': 80, 'math': 85, 'total': 255, 'avg': 85, 'order': 0},
  {'num': '2', 'name': '박제동', 'kor': 90, 'eng': 85, 'math': 90, 'total': 265, 'avg': 88, 'order': 0},
  {'num': '3', 'name': '홍길동', 'kor': 80, 'eng': 80, 'math': 80, 'total': 240, 'avg': 80, 'order': 0}
]
#학급 총점 평균
allsum = a[0]["avg"] + a[1]["avg"] + a[2]["avg"]
allavg = allsum/3
print("총 평균 : %.2f"%allavg)

#국어 평균
korsum = a[0]["kor"] + a[1]["kor"] + a[2]["kor"]
koravg = korsum/3
print("국어 평균 : %.2f"%koravg)

#영어 평균
engsum = a[0]["eng"] + a[1]["eng"] + a[2]["eng"]
engavg = engsum/3
print("영어 평균 : %.2f"%engavg)

#수학 평균
mathsum = a[0]["math"] + a[1]["math"] + a[2]["math"]
mathavg = mathsum/3
print("수학 평균 : %.2f"%mathavg)

x = int(input("숫자를 입력하세요 : "))
if x>0:
   print("양수!")
else:
   print("0 또는 음수!")

tran = int(input("가지고 있는 돈 : "))
if tran >=5000:
   print("택시를 탄다")
else:
   print("버스를 탄다")

grade = float(input("평점 : "))
if grade >= 4.3:
    print("장학금 수여 대상")
    print("축하드립니다")

num = int(input("숫자 입력 : "))
if num%2==0:
    print("짝수")
else:
    print("홀수")

su = int(input("숫자 입력 :"))
if su %2==0:
    print(f"{su}는 짝수")
    print("짝짝짝")
else:
    print(f"{su}는 홀수")
    print("홀홀홀")
print("if 문 끝")

age = int(input("나이 입력 : "))
height = int(input("키 입력 : "))
if age >= 40:
    if height >= 170:
        print("큰 키")
    else:
        print("보통 키")
else:
    if height >= 175:
        print("큰 키")
    else:
        print("보통 키")

x = int(input("시험 점수를 입력하시오 : "))
if x >= 90 :
  print("A")
elif x >= 80:
  print("B")
elif x >= 70:
  print("C")
elif x >= 60:
  print("D")
else:
  print("F")

score1 = int(input("필기성적을 입력하세요 : "))
score2 = int(input("실기성적을 입력하세요 : "))

if score1 >= 80 and score2 >= 80:
  print("합격!")
else:
  print("불합격")

id = str(input("아이디를 입력하세요 : "))
level = int(input("회원 레벨을 입력하세요 : "))

if level == 1 or id == "admin":
  print("관리자이다.")
else:
  print("관리자가 아님.")

name = str(input("이름을 입력하세요 : "))
if not name:
  print("이름이 입력되지 않았다.")
else :
  print(f"이름 : {name}")

pay = 3000
age = int(input("나이를 입력하세요 : "))

if age >=65 or age<7:
  pay = "무료"
  print(f"입장료 : {pay}")
else:
  print(f"입장료 : {pay}원")

passwd = 12345
a = int(input("비밀번호를 입력하세요 : "))
if a == passwd:
  print("passwd OK!")
else:
  print("passwd not OK!")

a = int(input("월을 입력하세요 : "))
if 3 <= a <= 5:
  print(f"{a}월은 봄입니다.")
elif 6 <= a <=8:
  print(f"{a}월은 여름입니다.")
elif 9 <= a <= 11:
  print(f"{a}월은 가을입다.")
else:
  print(f"{a}월은 겨울입니다.")

room = int(input("좌석 종류를 입력해 주세요(1:일반실,2:특실) : "))
if room == 1:
  print("일반실입니다.")
elif room == 2:
  print("특실입니다.")

eng = str(input("영어 알파벳을 입력하세요 : "))
b = "aeiou"
bb = ",".join(b)
if eng in bb:
  print(f"{eng}은(는) 모음이다.")
else:
  print(f"{eng}은(는) 자음이다.")

a = int(input("첫 번째 정수를 입력하세요 : "))
b = int(input("두 번째 정수를 입력하세요 : "))
c = int(input("세 번째 정수를 입력하세요 : "))
#print("입력된 세 수 %d,%d,%d 중에서 가장 큰 수는 %d입니다."%(a,b,c,max(a,b,c)))
if a >= b and a >= c:
  largest = a
elif b >= a and b >= c:
  largest = b
else:
  largest = c
print("입력된 세 수 %d,%d,%d 중에서 가장 큰 수는 %d입니다."%(a,b,c,largest))

print("""서비스 만족도: 
- 1 : 매우만족 
- 2 : 만족
- 3 : 불만족 서비스""")

service = int(input("만족도 입력(1 또는 2 또는 3) : "))
pay = int(input("음식값 입력(예:8000) : "))

if service == 1:
  a = "매우만족"
  great = int((pay) * 20/100)
  print(f"서비스 만족도 : {a}, 팁 : {great}원")
elif service == 2:
  b = "만족"
  good = int((pay) * 10/100)
  print(f"서비스 만족도 : {b}, 팁 : {good}원")
elif service == 3:
  c = "불만족 서비스"
  bad = int((pay) * 5/100)
  print(f"서비스 만족도 : {a}, 팁 : {bad}원")